#ifndef SRC_GAMES_ENDFIELD_VK_DEFERRED_LIGHTING_RENODX_INJECTION_HLSLI_
#define SRC_GAMES_ENDFIELD_VK_DEFERRED_LIGHTING_RENODX_INJECTION_HLSLI_

#include "../shared.h"

#define RENODX_CUSTOM_FOG      FOG_MODIFICATION
#define RENODX_CUBEMAP_AMBIENT shader_injection.cubemap_ambient_link
#define RENODX_IMPROVED_GTAO   IMPROVED_GTAO

#endif  // SRC_GAMES_ENDFIELD_VK_DEFERRED_LIGHTING_RENODX_INJECTION_HLSLI_
